In [1]:
import pandas as pd

In [7]:
df = pd.ExcelFile(r"C:\Users\ktjone1\Downloads\Bakken2018 Excel Well Workbook_2.xlsx")

In [3]:
import os

In [9]:
h = df.parse(0)

In [17]:
h = h.merge(t, left_on="UWI", right_on="UWI", how="outer")

In [16]:
t = df.parse("Formation")

In [18]:
h.describe()

,UWI,API Number,IC Number,Regulatory API,OS Indicator,Basin Code,Sub Basin Code,Permit Number,Depth Total Driller,Depth Total Logger,...,Gel/x-link (Gals),Fluid - Explosive (Gals),Fluid - Other (Gals),Total Fluid (gals),Total Proppant (lbs.) / Total Fluid (gal),Interpreter,Depth Top,Base Depth,Reason,Fault Type
count,7.612000e+04,7.612000e+04,1.700000e+01,7.058300e+04,0.0,76120.0,7.612000e+04,76115.000000,76120.000000,1235.000000,...,7.390600e+04,73906.0,7.390600e+04,7.390600e+04,73906.000000,0.0,63564.000000,6194.000000,0.0,0.0
mean,3.305174e+13,3.305174e+13,3.305376e+13,3.305172e+09,NaN,713200.0,1.000000e+11,25894.319070,20278.823450,16325.964372,...,3.235894e+06,0.0,3.164891e+05,4.245349e+06,1.215427,NaN,9289.748741,9031.053923,NaN,NaN
std,5.839296e+09,5.839296e+09,0.000000e+00,5.943447e+05,NaN,0.0,1.062507e+00,4999.760499,2101.757227,5046.556010,...,3.225679e+06,0.0,1.311679e+06,3.278156e+06,1.231149,NaN,1952.685657,780.169111,NaN,NaN
min,3.302503e+13,3.302503e+13,3.305376e+13,3.302502e+09,NaN,713200.0,1.000000e+11,3118.000000,9050.000000,9057.000000,...,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000,NaN,685.000000,1504.000000,NaN,NaN
25%,3.305304e+13,3.305304e+13,3.305376e+13,3.305304e+09,NaN,713200.0,1.000000e+11,22610.000000,20421.000000,10812.000000,...,3.820850e+05,0.0,0.000000e+00,2.197776e+06,0.943385,NaN,8296.000000,8946.000000,NaN,NaN
50%,3.305305e+13,3.305305e+13,3.305376e+13,3.305305e+09,NaN,713200.0,1.000000e+11,26533.000000,20839.000000,19819.000000,...,2.641128e+06,0.0,0.000000e+00,3.249918e+06,1.187936,NaN,9719.000000,9222.000000,NaN,NaN
75%,3.305306e+13,3.305306e+13,3.305376e+13,3.305306e+09,NaN,713200.0,1.000000e+11,29934.500000,21190.000000,20738.000000,...,4.307856e+06,0.0,0.000000e+00,5.229116e+06,1.486501,NaN,10918.000000,9466.000000,NaN,NaN
max,3.305308e+13,3.305308e+13,3.305376e+13,3.306101e+09,NaN,713200.0,1.000000e+11,33129.000000,27242.000000,25213.000000,...,2.407301e+07,0.0,1.289030e+07,2.409150e+07,101.178459,NaN,20433.000000,11278.000000,NaN,NaN

In [20]:
list(h)

['UWI',
 'Source_x',
 'API Number',
 'IC Number',
 'Regulatory API',
 'Operator Name',
 'Current Operator Name',
 'Lease Name',
 'Well Num',
 'Field Name',
 'Country Name',
 'State Name',
 'County Name',
 'OS Indicator',
 'Hole Direction',
 'Final Status',
 'Current Status',
 'Basin',
 'Basin Code',
 'Sub Basin',
 'Sub Basin Code',
 'Play Name',
 'Play Type',
 'Permit Number',
 'Permit Date',
 'Depth Total Driller',
 'Depth Total Logger',
 'Depth True Vertical',
 'Depth Whipstock',
 'Class Initial Name',
 'Class Initial Code',
 'Class Final Name',
 'Class Final Code',
 'Status Final Code',
 'Formation Projected Name',
 'Depth Total Projected',
 'Formation at TD Name',
 'PRODFit Formation at TD Name',
 'Formation Producing Name',
 'PRODFit Top Formation Producing Name',
 'PRODFit Base Formation Producing Name',
 'Elevation Reference Value',
 'Elevation Reference Datum',
 'Ground Elevation',
 'Date First Spud',
 'Date Spud',
 'Date Completion',
 'Date Rig Release',
 'Date Abandonment',
 'Date First Report',
 'Date Last Activity',
 'Depth Water Value',
 'Depth Water Datum',
 'Surface Latitude',
 'Surface Longitude',
 'Surface LL Source',
 'Proposed BH Latitude',
 'Proposed BH Longitude',
 'Proposed BH LL Source',
 'BH Latitude',
 'BH Longitude',
 'BH LL Source',
 'Activity Code',
 'Permit Filer Long',
 'Permit Phone',
 'Source_y',
 'Num Frac Stages',
 'Stages Avail',
 'Num Treatment Records',
 'Proppant - Sand (lbs)',
 'Proppant - Resin Coated Sand (lbs)',
 'Proppant - Ceramic (lbs)',
 'Proppant - Resin Coated Ceramic (lbs)',
 'Proppant - Sand, Ceramic (lbs)',
 'Proppant - Sand, Resin Coated Ceramic (lbs)',
 'Proppant - Sand, Ceramic, Resin Coated Sand (lbs)',
 'Proppant - Sand, Ceramic, Resin Coated Ceramic (lbs)',
 'Proppant - Sand, Resin Coated Sand, Ceramic, Resin Coated Ceramic (lbs)',
 'Proppant - Bauxite (lbs)',
 'Proppant - Walnut (lbs)',
 'Proppant - Marble (lbs)',
 'Proppant - Gravel (lbs)',
 'Proppant - Sand, Bauxite Ceramic (lbs)',
 'Proppant - Other (lbs)',
 'Total Proppant (lbs)',
 'Fluid/Water (Gals)',
 'Fluid - Slick Water (Gals)',
 'Fluid - Salt Water (Gals)',
 'Fluid - Foam (Gals)',
 'Fluid - Oil (Gals)',
 'Fluid - Potassium Chloride (Gals)',
 'Fluid - Surfactant (Gals)',
 'Fluid - Emulsion (Gals)',
 'N2/CO2 Gas (Gals)',
 'Acid (Gals)',
 'Gel/x-link (Gals)',
 'Fluid - Explosive (Gals)',
 'Fluid - Other (Gals)',
 'Total Fluid (gals)',
 'Total Proppant (lbs.) / Total Fluid (gal)',
 'Top Source',
 'Interpreter',
 'Code',
 'Name',
 'Depth Top',
 'Depth Top UOM',
 'Base Depth',
 'Base Depth UOM',
 'Source Name',
 'Reason',
 'Remark',
 'Fault Type']

In [27]:
test1 = [
    "UWI",
    "Operator Name",
    "Current Operator Name",
    "Lease Name",
    "Well Num",
    "OS Indicator",
    "Hole Direction",
    "Final Status",
    "Current Status",
    "Basin",
    "Basin Code",
    "Sub Basin",
    "Sub Basin Code",
    "Play Name",
    "Play Type",
    "Permit Date",
    "Depth Total Driller",
    "Depth Total Logger",
    "Depth True Vertical",
    "Depth Whipstock",
    "Class Initial Name",
    "Class Initial Code",
    "Class Final Name",
    "Class Final Code",
    "Status Final Code",
    "Formation Projected Name",
    "Depth Total Projected",
    "Formation at TD Name",
    "PRODFit Formation at TD Name",
    "Formation Producing Name",
    "PRODFit Top Formation Producing Name",
    "PRODFit Base Formation Producing Name",
    "Elevation Reference Value",
    "Elevation Reference Datum",
    "Ground Elevation",
    "Date First Spud",
    "Date Spud",
    "Date Completion",
    "Date Rig Release",
    "Date First Report",
    "Date Last Activity",
    "Depth Water Value",
    "Depth Water Datum",
    "Surface Latitude",
    "Surface Longitude",
    "Surface LL Source",
    "BH Latitude",
    "BH Longitude",
    "BH LL Source",
    "Activity Code",
    "Source_y",
    "Num Frac Stages",
    "Stages Avail",
    "Num Treatment Records",
    "Proppant - Sand (lbs)",
    "Proppant - Resin Coated Sand (lbs)",
    "Proppant - Ceramic (lbs)",
    "Proppant - Resin Coated Ceramic (lbs)",
    "Proppant - Sand, Ceramic (lbs)",
    "Proppant - Sand, Resin Coated Ceramic (lbs)",
    "Proppant - Sand, Ceramic, Resin Coated Sand (lbs)",
    "Proppant - Sand, Ceramic, Resin Coated Ceramic (lbs)",
    "Proppant - Sand, Resin Coated Sand, Ceramic, Resin Coated Ceramic (lbs)",
    "Proppant - Bauxite (lbs)",
    "Proppant - Walnut (lbs)",
    "Proppant - Marble (lbs)",
    "Proppant - Gravel (lbs)",
    "Proppant - Sand, Bauxite Ceramic (lbs)",
    "Proppant - Other (lbs)",
    "Total Proppant (lbs)",
    "Fluid/Water (Gals)",
    "Fluid - Slick Water (Gals)",
    "Fluid - Salt Water (Gals)",
    "Fluid - Foam (Gals)",
    "Fluid - Oil (Gals)",
    "Fluid - Potassium Chloride (Gals)",
    "Fluid - Surfactant (Gals)",
    "Fluid - Emulsion (Gals)",
    "N2/CO2 Gas (Gals)",
    "Acid (Gals)",
    "Gel/x-link (Gals)",
    "Fluid - Explosive (Gals)",
    "Fluid - Other (Gals)",
    "Total Fluid (gals)",
    "Total Proppant (lbs.) / Total Fluid (gal)",
    "Top Source",
    "Interpreter",
    "Code",
    "Name",
    "Depth Top",
    "Depth Top UOM",
    "Base Depth",
    "Base Depth UOM",
]

In [28]:
g = h[test1]

In [33]:
g.head()

,UWI,Operator Name,Current Operator Name,Lease Name,Well Num,OS Indicator,Hole Direction,Final Status,Current Status,Basin,...,Depth Top_y,Depth Base,PRODFit Top Formation,PRODFit Base Formation,Pressure Flowing Tubing,Pressure Flowing Casing,Pressure Shutin Tubing,Pressure Shutin Casing,Bottom Hole Run Depth,Pressure Bottom Hole
0,33025028850000,ENERPLUS RESOURCES (USA) CORPORATION,ENERPLUS RESOURCES (USA) CORPORATION,BARN,147-94-13A-24H,NaN,HORIZONTAL,OIL PRODUCER,A,WILLISTON BASIN,...,10928.0,19682.0,NaN,NaN,NaN,2600.0,NaN,NaN,NaN,NaN
1,33025028850000,ENERPLUS RESOURCES (USA) CORPORATION,ENERPLUS RESOURCES (USA) CORPORATION,BARN,147-94-13A-24H,NaN,HORIZONTAL,OIL PRODUCER,A,WILLISTON BASIN,...,10928.0,19682.0,NaN,NaN,NaN,2600.0,NaN,NaN,NaN,NaN
2,33025028850000,ENERPLUS RESOURCES (USA) CORPORATION,ENERPLUS RESOURCES (USA) CORPORATION,BARN,147-94-13A-24H,NaN,HORIZONTAL,OIL PRODUCER,A,WILLISTON BASIN,...,10928.0,19682.0,NaN,NaN,NaN,2600.0,NaN,NaN,NaN,NaN
3,33025028850000,ENERPLUS RESOURCES (USA) CORPORATION,ENERPLUS RESOURCES (USA) CORPORATION,BARN,147-94-13A-24H,NaN,HORIZONTAL,OIL PRODUCER,A,WILLISTON BASIN,...,10928.0,19682.0,NaN,NaN,NaN,2600.0,NaN,NaN,NaN,NaN
4,33025028850000,ENERPLUS RESOURCES (USA) CORPORATION,ENERPLUS RESOURCES (USA) CORPORATION,BARN,147-94-13A-24H,NaN,HORIZONTAL,OIL PRODUCER,A,WILLISTON BASIN,...,10928.0,19682.0,NaN,NaN,NaN,2600.0,NaN,NaN,NaN,NaN

In [34]:
i = df.parse("Completion")
g = g.merge(i, left_on="UWI", right_on="UWI", how="outer")

In [35]:
list(g)

['UWI',
 'Operator Name',
 'Current Operator Name',
 'Lease Name',
 'Well Num',
 'OS Indicator',
 'Hole Direction',
 'Final Status',
 'Current Status',
 'Basin',
 'Basin Code',
 'Sub Basin',
 'Sub Basin Code',
 'Play Name',
 'Play Type',
 'Permit Date',
 'Depth Total Driller',
 'Depth Total Logger',
 'Depth True Vertical',
 'Depth Whipstock',
 'Class Initial Name',
 'Class Initial Code',
 'Class Final Name',
 'Class Final Code',
 'Status Final Code',
 'Formation Projected Name',
 'Depth Total Projected',
 'Formation at TD Name',
 'PRODFit Formation at TD Name',
 'Formation Producing Name',
 'PRODFit Top Formation Producing Name',
 'PRODFit Base Formation Producing Name',
 'Elevation Reference Value',
 'Elevation Reference Datum',
 'Ground Elevation',
 'Date First Spud',
 'Date Spud',
 'Date Completion',
 'Date Rig Release',
 'Date First Report',
 'Date Last Activity',
 'Depth Water Value',
 'Depth Water Datum',
 'Surface Latitude',
 'Surface Longitude',
 'Surface LL Source',
 'BH Latitude',
 'BH Longitude',
 'BH LL Source',
 'Activity Code',
 'Source_y',
 'Num Frac Stages',
 'Stages Avail',
 'Num Treatment Records',
 'Proppant - Sand (lbs)',
 'Proppant - Resin Coated Sand (lbs)',
 'Proppant - Ceramic (lbs)',
 'Proppant - Resin Coated Ceramic (lbs)',
 'Proppant - Sand, Ceramic (lbs)',
 'Proppant - Sand, Resin Coated Ceramic (lbs)',
 'Proppant - Sand, Ceramic, Resin Coated Sand (lbs)',
 'Proppant - Sand, Ceramic, Resin Coated Ceramic (lbs)',
 'Proppant - Sand, Resin Coated Sand, Ceramic, Resin Coated Ceramic (lbs)',
 'Proppant - Bauxite (lbs)',
 'Proppant - Walnut (lbs)',
 'Proppant - Marble (lbs)',
 'Proppant - Gravel (lbs)',
 'Proppant - Sand, Bauxite Ceramic (lbs)',
 'Proppant - Other (lbs)',
 'Total Proppant (lbs)',
 'Fluid/Water (Gals)',
 'Fluid - Slick Water (Gals)',
 'Fluid - Salt Water (Gals)',
 'Fluid - Foam (Gals)',
 'Fluid - Oil (Gals)',
 'Fluid - Potassium Chloride (Gals)',
 'Fluid - Surfactant (Gals)',
 'Fluid - Emulsion (Gals)',
 'N2/CO2 Gas (Gals)',
 'Acid (Gals)',
 'Gel/x-link (Gals)',
 'Fluid - Explosive (Gals)',
 'Fluid - Other (Gals)',
 'Total Fluid (gals)',
 'Total Proppant (lbs.) / Total Fluid (gal)',
 'Top Source',
 'Interpreter',
 'Code',
 'Name',
 'Depth Top_x',
 'Depth Top UOM_x',
 'Base Depth',
 'Base Depth UOM',
 'Source_x',
 'Test Type',
 'Pressure Obs Number',
 'Fluid Type',
 'BH Pressure Obs Number',
 'Date',
 'Formation Top Name_x',
 'Formation Base Name_x',
 'Depth Top_y',
 'Depth Base_x',
 'PRODFit Top Formation',
 'PRODFit Base Formation',
 'Pressure Flowing Tubing',
 'Pressure Flowing Casing',
 'Pressure Shutin Tubing',
 'Pressure Shutin Casing',
 'Bottom Hole Run Depth',
 'Pressure Bottom Hole',
 'Source_y',
 'Number',
 'Completion Date',
 'Formation Top Name_y',
 'Formation Base Name_y',
 'Depth Top',
 'Depth Top UOM_y',
 'Depth Base_y',
 'Depth Base UOM',
 'PRODFit Formation Top Name',
 'PRODFit Formation Base Name',
 'Type',
 'Method',
 'Remark']

In [36]:
e = [
    "UWI",
    "Operator Name",
    "Current Operator Name",
    "Lease Name",
    "Well Num",
    "OS Indicator",
    "Hole Direction",
    "Final Status",
    "Current Status",
    "Basin",
    "Basin Code",
    "Sub Basin",
    "Sub Basin Code",
    "Play Name",
    "Play Type",
    "Permit Date",
    "Depth Total Driller",
    "Depth Total Logger",
    "Depth True Vertical",
    "Depth Whipstock",
    "Class Initial Name",
    "Class Initial Code",
    "Class Final Name",
    "Class Final Code",
    "Status Final Code",
    "Formation Projected Name",
    "Depth Total Projected",
    "Formation at TD Name",
    "PRODFit Formation at TD Name",
    "Formation Producing Name",
    "PRODFit Top Formation Producing Name",
    "PRODFit Base Formation Producing Name",
    "Elevation Reference Value",
    "Elevation Reference Datum",
    "Ground Elevation",
    "Date First Spud",
    "Date Spud",
    "Date Completion",
    "Date Rig Release",
    "Date First Report",
    "Date Last Activity",
    "Depth Water Value",
    "Depth Water Datum",
    "Surface Latitude",
    "Surface Longitude",
    "Surface LL Source",
    "BH Latitude",
    "BH Longitude",
    "BH LL Source",
    "Activity Code",
    "Source_y",
    "Num Frac Stages",
    "Stages Avail",
    "Num Treatment Records",
    "Proppant - Sand (lbs)",
    "Proppant - Resin Coated Sand (lbs)",
    "Proppant - Ceramic (lbs)",
    "Proppant - Resin Coated Ceramic (lbs)",
    "Proppant - Sand, Ceramic (lbs)",
    "Proppant - Sand, Resin Coated Ceramic (lbs)",
    "Proppant - Sand, Ceramic, Resin Coated Sand (lbs)",
    "Proppant - Sand, Ceramic, Resin Coated Ceramic (lbs)",
    "Proppant - Sand, Resin Coated Sand, Ceramic, Resin Coated Ceramic (lbs)",
    "Proppant - Bauxite (lbs)",
    "Proppant - Walnut (lbs)",
    "Proppant - Marble (lbs)",
    "Proppant - Gravel (lbs)",
    "Proppant - Sand, Bauxite Ceramic (lbs)",
    "Proppant - Other (lbs)",
    "Total Proppant (lbs)",
    "Fluid/Water (Gals)",
    "Fluid - Slick Water (Gals)",
    "Fluid - Salt Water (Gals)",
    "Fluid - Foam (Gals)",
    "Fluid - Oil (Gals)",
    "Fluid - Potassium Chloride (Gals)",
    "Fluid - Surfactant (Gals)",
    "Fluid - Emulsion (Gals)",
    "N2/CO2 Gas (Gals)",
    "Acid (Gals)",
    "Gel/x-link (Gals)",
    "Fluid - Explosive (Gals)",
    "Fluid - Other (Gals)",
    "Total Fluid (gals)",
    "Total Proppant (lbs.) / Total Fluid (gal)",
    "Top Source",
    "Interpreter",
    "Code",
    "Name",
    "Depth Top_x",
    "Depth Top UOM_x",
    "Base Depth",
    "Base Depth UOM",
    "Source_x",
    "Test Type",
    "Pressure Obs Number",
    "Fluid Type",
    "BH Pressure Obs Number",
    "Date",
    "Formation Top Name_x",
    "Formation Base Name_x",
    "Depth Top_y",
    "Depth Base_x",
    "PRODFit Top Formation",
    "PRODFit Base Formation",
    "Pressure Flowing Tubing",
    "Pressure Flowing Casing",
    "Pressure Shutin Tubing",
    "Pressure Shutin Casing",
    "Bottom Hole Run Depth",
    "Pressure Bottom Hole",
    "Source_y",
    "Number",
    "Formation Top Name_y",
    "Formation Base Name_y",
    "Depth Top",
    "Depth Top UOM_y",
    "Depth Base_y",
    "Depth Base UOM",
    "Type",
    "Method",
]

In [37]:
g = g[e]

In [38]:
g.describe()

,UWI,OS Indicator,Basin Code,Sub Basin Code,Depth Total Driller,Depth Total Logger,Depth True Vertical,Depth Whipstock,Depth Total Projected,PRODFit Formation at TD Name,...,PRODFit Base Formation,Pressure Flowing Tubing,Pressure Flowing Casing,Pressure Shutin Tubing,Pressure Shutin Casing,Bottom Hole Run Depth,Pressure Bottom Hole,Number,Depth Top,Depth Base_y
count,1.074280e+05,0.0,107428.0,1.074280e+05,107428.000000,23477.000000,83843.000000,322.000000,103031.000000,0.0,...,0.0,24681.000000,59209.000000,929.000000,207.000000,0.0,0.0,107397.000000,106901.000000,106901.000000
mean,3.305201e+13,NaN,713200.0,1.000000e+11,18381.403489,12476.152447,10877.239170,9519.950311,18656.436218,NaN,...,NaN,1391.115433,1641.936378,2070.263724,813.768116,NaN,NaN,5.373707,11243.250961,18140.055659
std,5.195915e+09,NaN,0.0,9.780976e-01,3941.081985,2221.305638,279.969943,1429.980257,3881.152539,NaN,...,NaN,885.791773,902.972699,373.995293,1054.464620,NaN,NaN,11.189311,813.153708,4267.080199
min,3.302503e+13,NaN,713200.0,1.000000e+11,9050.000000,9057.000000,9668.000000,7400.000000,9050.000000,NaN,...,NaN,0.000000,0.000000,700.000000,20.000000,NaN,NaN,1.000000,4760.000000,4982.000000
25%,3.305302e+13,NaN,713200.0,1.000000e+11,14340.000000,11020.000000,10696.000000,7404.000000,15167.000000,NaN,...,NaN,600.000000,950.000000,2175.000000,100.000000,NaN,NaN,1.000000,10853.000000,14222.000000
50%,3.305304e+13,NaN,713200.0,1.000000e+11,20627.000000,11020.000000,10903.000000,10060.000000,20721.000000,NaN,...,NaN,1275.000000,1579.000000,2175.000000,200.000000,NaN,NaN,1.000000,11185.000000,20586.000000
75%,3.305306e+13,NaN,713200.0,1.000000e+11,21055.000000,14340.000000,11096.000000,10337.000000,21121.000000,NaN,...,NaN,2082.000000,2300.000000,2175.000000,1800.000000,NaN,NaN,2.000000,11444.000000,21034.000000
max,3.305308e+13,NaN,713200.0,1.000000e+11,27242.000000,25213.000000,11557.000000,18339.000000,28497.000000,NaN,...,NaN,4000.000000,4700.000000,2175.000000,3450.000000,NaN,NaN,57.000000,22969.000000,27242.000000

In [39]:
g.UWI.value_counts()

33053005070000    13680
33053020800000     7749
33053020970000      312
33053014590000      252
33053022110000      240
33053011650000      195
33053012560000      168
33053018890000      165
33033002140000      144
33053074220000      140
33053017620000      140
33053074230000      136
33053073160000      136
33053073130000      136
33053070720000      132
33053070690000      132
33053073100000      128
33053019790000      128
33053074520000      128
33053065400000      126
33053070700000      124
33053070740000      124
33053034480000      120
33053049570000      120
33053060100000      120
33053048620000      116
33053067280000      110
33053024350000      108
33053035860000      108
33053068790000      108
                  ...
33053048030100        1
33053024810100        1
33053036170300        1
33053036080200        1
33053036320100        1
33053041930100        1
33053047850100        1
33053068070100        1
33053030670100        1
33053077030300        1
33053046900100        1
33053049360100        1
33053069160100        1
33053060640100        1
33025030210100        1
33053046150200        1
33053015270000        1
33053040120100        1
33053077630100        1
33053038940100        1
33053055140100        1
33053038310100        1
33053061910100        1
33053061510100        1
33053049140300        1
33053074330200        1
33053050500100        1
33053050220100        1
33053052990100        1
33053043870100        1
Name: UWI, dtype: int64